### ISSUE TITLE
Header image setup

### ISSUE THREAD

**Issue by bobvanluijt** [bobvanluijt/bobvanluijt.github.io#12]
Currently, Images look likes [this](https://cdn-images-1.medium.com/max/1600/1*AGlXcqZBqDW6oYiT7Wr7qw.png) or [this](https://cdn-images-1.medium.com/max/2000/1*hFHGoNt7efv5kxJIsl-JEg.jpeg). They should be transferred to CSS and HTML (including header as `<h1>` and subheader as `<h2>`.

**Comment by faizanvahevaria** [comment]
As Discussed, we will need header image files and it's HTML/CSS version, both.
Images to be referenced outside of the website.
HTML/CSS versions to be used inside the website.

**Comment by bobvanluijt** [comment]
Check, thanks @faizanvahevaria, I will create images myself.

**Comment by bobvanluijt** [comment]
- [ ] Would be nice if the header can be covering the background 100%
- [ ] for the page it can be CSS/HTML and not the image.

Reference image: 
<img width="1230" alt="screen shot 2018-08-18 at 17 38 54" src="https://user-images.githubusercontent.com/5509162/44300852-c207e600-a30d-11e8-9ee1-7e8362d6b66e.png">
