### ISSUE TITLE
Correct URLs

### ISSUE THREAD

**Issue by bobvanluijt** [bobvanluijt/bobvanluijt.github.io#16]
Set the urls to the title, all lowercase with dashes.

Example: `Some Random Title` becomes `some-random-title`

**Comment by faizanvahevaria** [comment]
@bobvanluijt 
The title of any post will be the file name.
Example:
FIle name:  2018-07-20-from-digital-to-physical-innovation.md
URL:  http://bob.wtf/blog/from-digital-to-physical-innovation/

If you don't want the file name to be the URL then you can define a new value called "slug" in each post's front-matter
Example:
```
---
layout: post
img : "13.jpeg"
title : "From Digital to Physical Innovation"
sub-title: "Why companies like Facebook and Google are building cities and neighbourhoods."
img_title: "From Digital to Physical Innovation"
img_sub_title: ""
bg_color: red;
tags: innovation digital-transformation digital-innovation-design
slug: "a-new-kind-of-url-of-your-choice"
---

```
