### ISSUE TITLE
Add tags to top menu

### ISSUE THREAD

**Issue by bobvanluijt** [bobvanluijt/bobvanluijt.github.io#18]
1. Add `tags` to the blog posts.
2. Show tags in the right top (next to about and contact). When selected a page with articles that respond to this tag should be shown.

**Comment by faizanvahevaria** [comment]
@bobvanluijt 
There are total 29 tags.
Do you want me to show those as a drop-down under the "Tags" menu item?

**Comment by bobvanluijt** [comment]
Ooo, I did not know this @faizanvahevaria. Good question.
Can you please make it like this: `/tags/[sometag]`? For example: `/tags/business`, if you go to this page all the pages that have the business-tag will be shown. I will decide later what I want to add to the top menu (I can do this myself).

**Comment by faizanvahevaria** [comment]
We have individual pages for each tag.
bob.wtf/tag/any-tag-here
and this URL will show the posts that are tagged with that particular tag.

One thing I don't have right now is bob.wtf/tags/
which should be index page showing a list of all tags or similar to tags archive.

I'll do that.

**Comment by bobvanluijt** [comment]
Awesome
