### ISSUE TITLE
Do you want mailchimp subscribe to newsletter form on each post?

### ISSUE THREAD

**Issue by faizanvahevaria** [bobvanluijt/bobvanluijt.github.io#19]
You have a link which on the existing blog that leads to mailchimp so user can subscribe.

Do you want a form rather than just a link on each blog post?
@bobvanluijt

**Comment by bobvanluijt** [comment]
Hi @faizanvahevaria, I think I will add something myself because I'm not sure how to do this yet. Thanks, though.
