### ISSUE TITLE
Create All individual Pages

### ISSUE THREAD

**Issue by faizanvahevaria** [bobvanluijt/bobvanluijt.github.io#7]

**Comment by faizanvahevaria** [comment]
@bobvanluijt 
Waiting for the content from your side.

**Comment by bobvanluijt** [comment]
Send it to you yesterday via up work @faizanvahevaria, did you see this?

**Comment by faizanvahevaria** [comment]
@bobvanluijt 
This is for "Contact", "About", and other individual pages, not the posts.

**Comment by bobvanluijt** [comment]
o, sorry, my misunderstanding. For now, they can stay empty, I'll fill them myself.
